
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Emprunte extends javax.swing.JFrame {

    /**
     * Creates new form Emprunte
     */
    public Emprunte() {
        initComponents();
        isbn.setVisible(false);
    labisn.setVisible(false);
    isbn1.setVisible(false);
    labisn1.setVisible(false);
    supp.setVisible(false);
    combchoix.setVisible(false);
    rech.setVisible(false);
    tablemodele = (DefaultTableModel) tableLivre.getModel();
    tableLivre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gestionLivre = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        choix = new javax.swing.JComboBox<>();
        isbn = new javax.swing.JTextField();
        labisn = new javax.swing.JLabel();
        supp = new javax.swing.JButton();
        combchoix = new javax.swing.JComboBox<>();
        rech = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivre = new javax.swing.JTable();
        Retour = new javax.swing.JButton();
        isbn1 = new javax.swing.JTextField();
        labisn1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gestionLivre.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        gestionLivre.setText("Gestion des Emprunts");

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ajouter Emprunt", "Supprimer Emprunt", "Rechercher Emprunt", "Afficher tous  les Emprunts", " " }));
        choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixActionPerformed(evt);
            }
        });

        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });

        labisn.setText("idkindles:");

        supp.setText("Supprimer");
        supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppActionPerformed(evt);
            }
        });

        combchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idkindles", "matricule" }));

        rech.setText("Rechercher");
        rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechActionPerformed(evt);
            }
        });

        tableLivre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "matriculeClient", " idKindles", "dateEmprunt"
            }
        ));
        jScrollPane1.setViewportView(tableLivre);

        Retour.setText("< Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        isbn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbn1ActionPerformed(evt);
            }
        });

        labisn1.setText("Matricule client:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(428, 428, 428))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labisn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(labisn1)
                        .addGap(88, 88, 88)
                        .addComponent(isbn1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(supp)
                        .addGap(36, 36, 36)
                        .addComponent(rech)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(gestionLivre))
                    .addComponent(Retour))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valider))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labisn)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supp)
                    .addComponent(rech)
                    .addComponent(isbn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labisn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        switch(choix.getSelectedItem().toString()){
            case "Ajouter Emprunt" +
"":
            {
                AddEmprunt frameXe = new AddEmprunt();
                frameXe.setVisible(true);
                tableLivre.setVisible(false);

            }
            break;

            case "Supprimer Emprunt": {
                isbn.setVisible(true);
                labisn.setVisible(true);
                isbn1.setVisible(true);
                labisn1.setVisible(true);
                supp.setVisible(true);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tableLivre.setVisible(false);
            }
            break;

            case "Rechercher Emprunt":{

                labisn.setVisible(false);
                labisn1.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(true);
                isbn.setVisible(true);
                isbn1.setVisible(false);
                rech.setVisible(true);
                tableLivre.setVisible(true);

            }
            break;
            case "Afficher tous  les Emprunts":{
                tableLivre.setVisible(true);
                isbn.setVisible(false);
                labisn.setVisible(false);
                isbn1.setVisible(false);
                labisn1.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tablemodele.setRowCount(0);
                GestionEmprunts gest = new GestionEmprunts();
                LinkedList<Emprunt> livres = new LinkedList<>();
               
            try {
                livres = gest.afficherTousLesEmprunts();
            } catch (SQLException ex) {
                Logger.getLogger(Emprunte.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                for (Emprunt livre : livres) {
                    Object[] rowData = {
                        livre.getMatriculeClient(),
                        livre.getIdKindles(),
                        livre.getDateEmprunt(),
                        
                    };
                    tablemodele.addRow(rowData);

                }
                break;}
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixActionPerformed

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    private void suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppActionPerformed
        String isbne=isbn.getText();
        String isbne1=isbn1.getText();

        GestionEmprunts gest=new GestionEmprunts();

        try {
            boolean a=gest.supprimerEmprunt( isbne1, isbne);
        } catch (SQLException ex) {

            
        }
        isbn.setText("");
            isbn1.setText("");
    }//GEN-LAST:event_suppActionPerformed

    private void rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechActionPerformed

        tablemodele.setRowCount(0); // Clear the table before populating it

        String a = isbn.getText();
        isbn.setText("");
        GestionEmprunts gest = new GestionEmprunts();
        LinkedList<Emprunt> livres = new LinkedList<>(); // Initialize livres as an empty list

        switch (combchoix.getSelectedItem().toString()) {
            case "idkindles":

            {
              
            try {
                livres = gest.getEmpruntsByIdKindles(a);
            } catch (SQLException ex) {
                Logger.getLogger(Emprunte.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
            break;

            case "matricule":

            {
                
            try {
                livres = gest.getEmpruntsByMatriculeClient(a);
            } catch (SQLException ex) {
                Logger.getLogger(Emprunte.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                    
            }

            break;

            

        }

        for (Emprunt livre : livres) {
            Object[] rowData = {
                livre.getMatriculeClient(),
                livre.getIdKindles(),
                livre.getDateEmprunt(),

            };
            tablemodele.addRow(rowData);
        }
    }//GEN-LAST:event_rechActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        JFrameX frameX = new JFrameX();
        frameX.setVisible(true);
    }//GEN-LAST:event_RetourActionPerformed

    private void isbn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprunte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprunte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprunte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprunte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emprunte().setVisible(true);
            }
        });
    }
DefaultTableModel tablemodele;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JButton Valider;
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JComboBox<String> combchoix;
    private javax.swing.JLabel gestionLivre;
    private javax.swing.JTextField isbn;
    private javax.swing.JTextField isbn1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labisn;
    private javax.swing.JLabel labisn1;
    private javax.swing.JButton rech;
    private javax.swing.JButton supp;
    private javax.swing.JTable tableLivre;
    // End of variables declaration//GEN-END:variables
}
