
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Magazine extends javax.swing.JFrame {

    /**
     * Creates new form Magazine
     */
    public Magazine() {
        initComponents();
        isbn.setVisible(false);
    labisn.setVisible(false);
    supp.setVisible(false);
    combchoix.setVisible(false);
    rech.setVisible(false);
    tablemodele = (DefaultTableModel) tableLivre.getModel();
    tableLivre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour = new javax.swing.JButton();
        gestionLivre = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        choix = new javax.swing.JComboBox<>();
        isbn = new javax.swing.JTextField();
        labisn = new javax.swing.JLabel();
        supp = new javax.swing.JButton();
        combchoix = new javax.swing.JComboBox<>();
        rech = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivre = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Retour.setText("< Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        gestionLivre.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        gestionLivre.setText("Gestion des Magazines");

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ajouter Magazin", "Supprimer Magazin", "Rechercher Magazin", "Afficher tous Magazin", " " }));
        choix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixActionPerformed(evt);
            }
        });

        isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnActionPerformed(evt);
            }
        });

        labisn.setText("ISBN:");

        supp.setText("Supprimer");
        supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppActionPerformed(evt);
            }
        });

        combchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "frequenceDePublication", "genre", "numeroDeMgazin", "ISBN", "titre", "Editeur", "anneeEdition", "URL", "favorie", "recommande", " " }));

        rech.setText("Rechercher");
        rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechActionPerformed(evt);
            }
        });

        tableLivre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "frequenceDePublication", "genre", "numeroDeMgazin", "ISBN", "titre", "Editeur ", "anneeEdition", "URL", "favorie", "recommande", "Auteur1", "Auteur2", "Auteur3", "Auteur4", "Auteur5"
            }
        ));
        jScrollPane1.setViewportView(tableLivre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(labisn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(340, 340, 340)
                .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206)
                .addComponent(supp)
                .addGap(36, 36, 36)
                .addComponent(rech)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(428, 428, 428))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(gestionLivre))
                    .addComponent(Retour))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Valider))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labisn)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supp)
                    .addComponent(rech))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Documents frameX = new Documents();
        frameX.setVisible(true);
    }//GEN-LAST:event_RetourActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        switch(choix.getSelectedItem().toString()){
            case "Ajouter Magazin":
            {
                AddMagazin frameXe = new AddMagazin();
                frameXe.setVisible(true);
                tableLivre.setVisible(false);

            }
            break;

            case "Supprimer Magazin": {
                isbn.setVisible(true);
                labisn.setVisible(true);
                supp.setVisible(true);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tableLivre.setVisible(false);
            }
            break;

            case "Rechercher Magazin":{

                labisn.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(true);
                isbn.setVisible(true);
                rech.setVisible(true);
                tableLivre.setVisible(true);

            }
            break;
            case "Afficher tous Magazin":{
                tableLivre.setVisible(true);
                isbn.setVisible(false);
                labisn.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tablemodele.setRowCount(0);
                GestionMagazin gest = new GestionMagazin();
                LinkedList<Magazin> livres = new LinkedList<>();
            try {
                livres = gest.afficherTousLesMagazins();
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
                for (Magazin livre : livres) {
                    Object[] rowData = {
                        livre.getFrequenceDePublication(),
                        livre.getGenre(),
                        livre.getNumeroDeMgazin(),
                        livre.getISBN(),
                        livre.getTitre(),
                        livre.getEditeur(),
                        livre.getAnneeEdition(),
                        livre.getURL(),
                        livre.getFavorie(),
                        livre.getRecommande(),
                        livre.getAuteur1(),
                        livre.getAuteur2(),
                        livre.getAuteur3(),
                        livre.getAuteur4(),
                        livre.getAuteur5()
                    };
                    tablemodele.addRow(rowData);

                }
                break;}
        }

    }//GEN-LAST:event_ValiderActionPerformed

    private void choixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixActionPerformed

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    private void suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppActionPerformed
        String isbne=isbn.getText();

        GestionMagazin gest=new GestionMagazin();

        try {
            boolean a=gest.supprimerMagazin(isbne);
        } catch (SQLException ex) {
             Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
        }
        isbn.setText("");

    }//GEN-LAST:event_suppActionPerformed

    private void rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechActionPerformed

        tablemodele.setRowCount(0); // Clear the table before populating it

        String a = isbn.getText();
        isbn.setText("");
        GestionMagazin gest = new GestionMagazin();
        LinkedList<Magazin> livres = new LinkedList<>(); // Initialize livres as an empty list

        switch (combchoix.getSelectedItem().toString()) {
            case "frequenceDePublication":
            try {
                livres = gest.getArticleByFrequenceDePublication(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "genre":
            try {
                livres = gest.getArticleByGenre(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "numeroDeMgazin":
            try {
                livres = gest.getArticleByNumeroDeMgazin(Integer.parseInt(a));
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "ISBN":
            try {
                livres = gest.getMagazinsByISBN(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "titre":
            try {
                livres = gest.getMagazinsByTitre(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "Editeur":
            try {
                livres = gest.getMagazinsByEditeur(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "anneeEdition":
            try {
                livres = gest.getMagazinsByAnneeEdition(Integer.parseInt(a));
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "URL":
            try {
                livres = gest.getMagazinsByURL(a);
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "favorie":
            try {
                livres = gest.getMagazinsByFavorie(Integer.parseInt(a));
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
            case "recommande":
            try {
                livres = gest.getMagazinsByRecommande(Integer.parseInt(a));
            } catch (SQLException ex) {
                Logger.getLogger(Magazine.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            default:
            break;
        }

        for (Magazin livre : livres) {
            Object[] rowData = {
                livre.getFrequenceDePublication(),
                livre.getGenre(),
                livre.getNumeroDeMgazin(),
                livre.getISBN(),
                livre.getTitre(),
                livre.getEditeur(),
                livre.getAnneeEdition(),
                livre.getURL(),
                livre.getFavorie(),
                livre.getRecommande(),
                livre.getAuteur1(),
                livre.getAuteur2(),
                livre.getAuteur3(),
                livre.getAuteur4(),
                livre.getAuteur5()
            };
            tablemodele.addRow(rowData);
        }

    }//GEN-LAST:event_rechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Magazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Magazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Magazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Magazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Magazine().setVisible(true);
            }
        });
    }DefaultTableModel tablemodele;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JButton Valider;
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JComboBox<String> combchoix;
    private javax.swing.JLabel gestionLivre;
    private javax.swing.JTextField isbn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labisn;
    private javax.swing.JButton rech;
    private javax.swing.JButton supp;
    private javax.swing.JTable tableLivre;
    // End of variables declaration//GEN-END:variables
}
