
import java.lang.System.Logger;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Romane extends javax.swing.JFrame {

    /**
     * Creates new form Romane
     */
    public Romane() {
        initComponents();
        isbn.setVisible(false);
    labisn.setVisible(false);
    supp.setVisible(false);
    combchoix.setVisible(false);
    rech.setVisible(false);
    tablemodele = (DefaultTableModel) tableLivre.getModel();
    tableLivre.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choix = new javax.swing.JComboBox<>();
        Valider = new javax.swing.JButton();
        combchoix = new javax.swing.JComboBox<>();
        labisn = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        supp = new javax.swing.JButton();
        gestion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivre = new javax.swing.JTable();
        Retour = new javax.swing.JButton();
        rech = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        choix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ajouter Roman", "Supprimer Roman", "Rechercher Roman", "Afficher tous les Romans", " " }));

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });

        combchoix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "genre", "nbChapitres", "ISBN", "titre", "Editeur", "anneeEdition", "URL", "favorie", "recommande" }));

        labisn.setText("ISBN:");

        supp.setText("Supprimer");
        supp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppActionPerformed(evt);
            }
        });

        gestion.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        gestion.setText("Gestion des Romans");

        tableLivre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "genre", "nbChapitres", "ISBN", "titre", "Editeur", "anneeEdition", "URL", "favorie", "recommande", "Auteur1", "Auteur2", "Auteur3", "Auteur4", "Auteur5"
            }
        ));
        jScrollPane1.setViewportView(tableLivre);

        Retour.setText("< Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        rech.setText("Rechercher");
        rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Retour)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rech)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Valider)
                    .addGap(102, 102, 102))
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82)
                            .addComponent(labisn)
                            .addGap(118, 118, 118)
                            .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(gestion))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supp)
                    .addGap(155, 155, 155)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(rech)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(gestion)
                    .addGap(43, 43, 43)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(choix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Valider))
                    .addGap(32, 32, 32)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combchoix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labisn)
                        .addComponent(supp)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(232, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        tablemodele.setRowCount(0);
        String a = isbn.getText();
        isbn.setText("");
        GestionRoman gest = new GestionRoman();
        LinkedList<Roman> articles = new LinkedList<>();
        switch(choix.getSelectedItem().toString()){
            case "Ajouter Roman":
            {
                AddRoman frameXe = new AddRoman();
                frameXe.setVisible(true);
                tableLivre.setVisible(false);

            }
            break;

            case "Supprimer Roman": {
                isbn.setVisible(true);
                labisn.setVisible(true);
                supp.setVisible(true);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tableLivre.setVisible(false);
            }
            break;

            case "Rechercher Roman":{

                labisn.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(true);
                isbn.setVisible(true);
                rech.setVisible(true);
                tableLivre.setVisible(true);

            }
            break;
            case "Afficher tous les Romans":{
                tableLivre.setVisible(true);
                isbn.setVisible(false);
                labisn.setVisible(false);
                supp.setVisible(false);
                combchoix.setVisible(false);

                rech.setVisible(false);
                tablemodele.setRowCount(0);
                GestionRoman geste = new GestionRoman();
                LinkedList<Roman> articless = new LinkedList<>();
            try {
                articless = geste.afficherTousLesRomans();
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
            }
                for (Roman livre : articless) {
                    Object[] rowData = {
                        livre.getGenre(),
                        livre.getNbChapitres(),
                        livre.getISBN(),
                        livre.getTitre(),
                        livre.getEditeur(),
                        livre.getAnneeEdition(),
                        livre.getURL(),
                        livre.getFavorie(),
                        livre.getRecommande(),
                        livre.getAuteur1(),
                        livre.getAuteur2(),
                        livre.getAuteur3(),
                        livre.getAuteur4(),
                        livre.getAuteur5()
                    };
                    tablemodele.addRow(rowData);

                }
                break;}}
    }//GEN-LAST:event_ValiderActionPerformed

    private void suppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppActionPerformed
        String isbne=isbn.getText();

        GestionRoman gest=new GestionRoman();

        try {
            boolean a=gest.supprimerRoman(isbne);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
        }
        isbn.setText("");
    }//GEN-LAST:event_suppActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Documents frameX = new Documents();
        frameX.setVisible(true);
    }//GEN-LAST:event_RetourActionPerformed

    private void rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechActionPerformed
        tablemodele.setRowCount(0); // Clear the table before populating it

        String a = isbn.getText();
        isbn.setText("");
        GestionRoman gest = new GestionRoman();
        LinkedList<Roman> livres = new LinkedList<>(); // Initialize livres as an empty list

        switch (combchoix.getSelectedItem().toString()) {
            case "genre":
            {
                try {
                    livres = gest.getRomanByGenre(a);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

        case "nbChapitres":
            {
                try {
                    livres = gest.getRomansByNBChapitres(Integer.parseInt(a));
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

            case "ISBN":
            {
                try {
                    livres = gest.getRomansByISBN(a);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            break;

            case "titre":
            {  
                try {
                    livres = gest.getRomansByTitre(a);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            break;

            case "Editeur":
             try {
                    livres = gest.getRomansByEditeur(a);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            break;
            case "anneeEdition":
            try {
                    livres = gest.getRomansByAnneeEdition(Integer.parseInt(a));
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            break;
            case "URL":
           try {
                    livres = gest.getRomansByURL(a);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            break;
            case "favorie":
            try {
                    livres = gest.getRomansByFavorie(Integer.parseInt(a));
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
                }
            break;
            case "recommande":
            try {
                livres = gest.getRomansByRecommande(Integer.parseInt(a));
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(Romane.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;

            default:
            break;
        }

        for (Roman livre : livres) {
            Object[] rowData = {
                livre.getGenre(),
                livre.getNbChapitres(),
                livre.getISBN(),
                livre.getTitre(),
                livre.getEditeur(),
                livre.getAnneeEdition(),
                livre.getURL(),
                livre.getFavorie(),
                livre.getRecommande(),
                livre.getAuteur1(),
                livre.getAuteur2(),
                livre.getAuteur3(),
                livre.getAuteur4(),
                livre.getAuteur5()
            };
            tablemodele.addRow(rowData);
        }
    }//GEN-LAST:event_rechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Romane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Romane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Romane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Romane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Romane().setVisible(true);
            }
        });
    }DefaultTableModel tablemodele;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JButton Valider;
    private javax.swing.JComboBox<String> choix;
    private javax.swing.JComboBox<String> combchoix;
    private javax.swing.JLabel gestion;
    private javax.swing.JTextField isbn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labisn;
    private javax.swing.JButton rech;
    private javax.swing.JButton supp;
    private javax.swing.JTable tableLivre;
    // End of variables declaration//GEN-END:variables
}
